/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const EnrollmentRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEnrollmentRequests' : IDL.Func(
      [],
      [IDL.Vec(EnrollmentRequest)],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitEnrollmentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const EnrollmentRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEnrollmentRequests' : IDL.Func(
        [],
        [IDL.Vec(EnrollmentRequest)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitEnrollmentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };